# Generated by Django 4.2.5 on 2023-09-23 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Aadhar Card", "Aadhar Card"),
                            ("Pan Card", "Pan Card"),
                            ("Voter ID Card", "Voter ID Card"),
                        ],
                        max_length=50,
                        verbose_name="service",
                    ),
                ),
                ("phone", models.IntegerField(verbose_name="phone")),
                ("price", models.BigIntegerField(verbose_name="price")),
                ("paid", models.BigIntegerField(verbose_name="paid")),
                ("bal", models.BigIntegerField(verbose_name="bal")),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 9, 23, 7, 43, 53, 3654)
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="completed"),
                ),
                ("cmt", models.CharField(max_length=200, verbose_name="comments")),
            ],
        ),
    ]
